export { authRoutes } from './auth.js'
export { questionRoutes } from './questions.js'
export { testRoutes } from './test.js'
export { chatbotRoutes } from './chatbot.js'
export { userRoutes } from './user.js'